version: "3.8"

services:
  app_prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      MODE: ${PROD_MODE:-DEV}
      BINDING: "0.0.0.0"
      POSTGRES_DATABASE: ${POSTGRES_PROD_DB:-mindmapper-backend-prod}
      POSTGRES_HOST: ${POSTGRES_PROD_HOST:-postgres_prod}
      POSTGRES_PASSWORD: ${POSTGRES_PROD_PASSWORD:-mindmapper-password}
      POSTGRES_PORT: ${POSTGRES_PROD_PROD_PORT:-5432}
      POSTGRES_SSL_REJECT_UNAUTHORIZED: ${POSTGRES_SSL_REJECT_UNAUTHORIZED:-true}
      POSTGRES_USER: ${POSTGRES_PROD_USER:-mindmapper-user}
    ports:
      - "${APP_PROD_PORT:-80}:3000"
    depends_on:
      - postgres_prod

  postgres_prod:
    image: postgres:12-alpine
    # Pass config parameters to the postgres server.
    # Find more information below when you need to generate the ssl-relevant file your self
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_PROD_DB:-mindmapper-backend-prod}
      POSTGRES_PASSWORD: ${POSTGRES_PROD_PASSWORD:-mindmapper-password}
      POSTGRES_USER: ${POSTGRES_PROD_USER:-mindmapper-user}
    # Exposing the port is not needed unless you want to access this database instance from the host.
    # Be careful when other postgres docker container are running on the same port
    ports:
      - "${POSTGRES_PROD_PORT:-5432}:5432"
    volumes:
      # To setup an ssl-enabled postgres server locally, you need to generate a self-signed ssl certificate.
      # See README.md for more information.
      # Mount the ssl_cert_file and ssl_key_file into the docker container.
      - ./ca/server.crt:/var/lib/postgresql/server.crt
      - ./ca/server.key:/var/lib/postgresql/server.key
      - postgres_prod_data:/var/lib/postgresql/data/pgdata

volumes:
  postgres_prod_data:
